from typing import Dict

from .style import MudStyle
from rich.theme import Theme

DEFAULT_STYLES: Dict[str, MudStyle] = {
    "none": MudStyle.null(),
    "reset": MudStyle(
        color="default",
        bgcolor="default",
        dim=False,
        bold=False,
        italic=False,
        underline=False,
        blink=False,
        blink2=False,
        reverse=False,
        conceal=False,
        strike=False,
    ),
    "dim": MudStyle(dim=True),
    "bright": MudStyle(dim=False),
    "bold": MudStyle(bold=True),
    "strong": MudStyle(bold=True),
    "code": MudStyle(reverse=True, bold=True),
    "italic": MudStyle(italic=True),
    "emphasize": MudStyle(italic=True),
    "underline": MudStyle(underline=True),
    "blink": MudStyle(blink=True),
    "blink2": MudStyle(blink2=True),
    "reverse": MudStyle(reverse=True),
    "strike": MudStyle(strike=True),
    "black": MudStyle(color="black"),
    "red": MudStyle(color="red"),
    "green": MudStyle(color="green"),
    "yellow": MudStyle(color="yellow"),
    "magenta": MudStyle(color="magenta"),
    "cyan": MudStyle(color="cyan"),
    "white": MudStyle(color="white"),
    "inspect.attr": MudStyle(color="yellow", italic=True),
    "inspect.attr.dunder": MudStyle(color="yellow", italic=True, dim=True),
    "inspect.callable": MudStyle(bold=True, color="red"),
    "inspect.def": MudStyle(italic=True, color="bright_cyan"),
    "inspect.error": MudStyle(bold=True, color="red"),
    "inspect.equals": MudStyle(),
    "inspect.help": MudStyle(color="cyan"),
    "inspect.doc": MudStyle(dim=True),
    "inspect.value.border": MudStyle(color="green"),
    "live.ellipsis": MudStyle(bold=True, color="red"),
    "layout.tree.row": MudStyle(dim=False, color="red"),
    "layout.tree.column": MudStyle(dim=False, color="blue"),
    "logging.keyword": MudStyle(bold=True, color="yellow"),
    "logging.level.notset": MudStyle(dim=True),
    "logging.level.debug": MudStyle(color="green"),
    "logging.level.info": MudStyle(color="blue"),
    "logging.level.warning": MudStyle(color="red"),
    "logging.level.error": MudStyle(color="red", bold=True),
    "logging.level.critical": MudStyle(color="red", bold=True, reverse=True),
    "log.level": MudStyle.null(),
    "log.time": MudStyle(color="cyan", dim=True),
    "log.message": MudStyle.null(),
    "log.path": MudStyle(dim=True),
    "repr.ellipsis": MudStyle(color="yellow"),
    "repr.indent": MudStyle(color="green", dim=True),
    "repr.error": MudStyle(color="red", bold=True),
    "repr.str": MudStyle(color="green", italic=False, bold=False),
    "repr.brace": MudStyle(bold=True),
    "repr.comma": MudStyle(bold=True),
    "repr.ipv4": MudStyle(bold=True, color="bright_green"),
    "repr.ipv6": MudStyle(bold=True, color="bright_green"),
    "repr.eui48": MudStyle(bold=True, color="bright_green"),
    "repr.eui64": MudStyle(bold=True, color="bright_green"),
    "repr.tag_start": MudStyle(bold=True),
    "repr.tag_name": MudStyle(color="bright_magenta", bold=True),
    "repr.tag_contents": MudStyle(color="default"),
    "repr.tag_end": MudStyle(bold=True),
    "repr.attrib_name": MudStyle(color="yellow", italic=False),
    "repr.attrib_equal": MudStyle(bold=True),
    "repr.attrib_value": MudStyle(color="magenta", italic=False),
    "repr.number": MudStyle(color="cyan", bold=True, italic=False),
    "repr.bool_true": MudStyle(color="bright_green", italic=True),
    "repr.bool_false": MudStyle(color="bright_red", italic=True),
    "repr.none": MudStyle(color="magenta", italic=True),
    "repr.url": MudStyle(underline=True, color="bright_blue", italic=False, bold=False),
    "repr.uuid": MudStyle(color="bright_yellow", bold=False),
    "rule.line": MudStyle(color="bright_green"),
    "rule.text": MudStyle.null(),
    "prompt": MudStyle.null(),
    "prompt.choices": MudStyle(color="magenta", bold=True),
    "prompt.default": MudStyle(color="cyan", bold=True),
    "prompt.invalid": MudStyle(color="red"),
    "prompt.invalid.choice": MudStyle(color="red"),
    "pretty": MudStyle.null(),
    "scope.border": MudStyle(color="blue"),
    "scope.key": MudStyle(color="yellow", italic=True),
    "scope.key.special": MudStyle(color="yellow", italic=True, dim=True),
    "scope.equals": MudStyle(color="red"),
    "repr.path": MudStyle(color="magenta"),
    "repr.filename": MudStyle(color="bright_magenta"),
    "table.header": MudStyle(bold=True),
    "table.footer": MudStyle(bold=True),
    "table.cell": MudStyle.null(),
    "table.title": MudStyle(italic=True),
    "table.caption": MudStyle(italic=True, dim=True),
    "traceback.error": MudStyle(color="red", italic=True),
    "traceback.border.syntax_error": MudStyle(color="bright_red"),
    "traceback.border": MudStyle(color="red"),
    "traceback.text": MudStyle.null(),
    "traceback.title": MudStyle(color="red", bold=True),
    "traceback.exc_type": MudStyle(color="bright_red", bold=True),
    "traceback.exc_value": MudStyle.null(),
    "traceback.offset": MudStyle(color="bright_red", bold=True),
    "bar.back": MudStyle(color="grey23"),
    "bar.complete": MudStyle(color="rgb(249,38,114)"),
    "bar.finished": MudStyle(color="rgb(114,156,31)"),
    "bar.pulse": MudStyle(color="rgb(249,38,114)"),
    "progress.description": MudStyle.null(),
    "progress.filesize": MudStyle(color="green"),
    "progress.filesize.total": MudStyle(color="green"),
    "progress.download": MudStyle(color="green"),
    "progress.elapsed": MudStyle(color="yellow"),
    "progress.percentage": MudStyle(color="magenta"),
    "progress.remaining": MudStyle(color="cyan"),
    "progress.data.speed": MudStyle(color="red"),
    "progress.spinner": MudStyle(color="green"),
    "status.spinner": MudStyle(color="green"),
    "tree": MudStyle(),
    "tree.line": MudStyle(),
}

MARKDOWN_STYLES = {
    "markdown.paragraph": MudStyle(),
    "markdown.text": MudStyle(),
    "markdown.emph": MudStyle(italic=True),
    "markdown.strong": MudStyle(bold=True),
    "markdown.code": MudStyle(bgcolor="black", color="bright_white"),
    "markdown.code_block": MudStyle(dim=True, color="cyan", bgcolor="black"),
    "markdown.block_quote": MudStyle(color="magenta"),
    "markdown.list": MudStyle(color="cyan"),
    "markdown.item": MudStyle(),
    "markdown.item.bullet": MudStyle(color="yellow", bold=True),
    "markdown.item.number": MudStyle(color="yellow", bold=True),
    "markdown.hr": MudStyle(color="yellow"),
    "markdown.h1.border": MudStyle(),
    "markdown.h1": MudStyle(bold=True),
    "markdown.h2": MudStyle(bold=True, underline=True),
    "markdown.h3": MudStyle(bold=True),
    "markdown.h4": MudStyle(bold=True, dim=True),
    "markdown.h5": MudStyle(underline=True),
    "markdown.h6": MudStyle(italic=True),
    "markdown.h7": MudStyle(italic=True, dim=True),
    "markdown.link": MudStyle(color="bright_blue"),
    "markdown.link_url": MudStyle(color="blue"),
}


DEFAULT_STYLES.update(MARKDOWN_STYLES)


DEFAULT = Theme(DEFAULT_STYLES)
